# Generated by Django 4.1.2 on 2022-10-10 19:45

from django.db import migrations, models
import nuremberg.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0007_alter_transcriptpage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptpage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=nuremberg.core.storages.TranscriptStorage(), upload_to='nuremberg-transcripts'),
        ),
    ]
