version: '2'

services:

  solr:
    image: solr:8
    volumes:
      # NAMED VOLUMES
      - solr_data:/var/solr

  web:
    build:
      context: ./web
    tty: true
    command: bash
    volumes:
      # BIND MOUNTS
      - ./web:/nuremberg
    environment:
      # let Django load Docker-specific settings conditionally
      - DOCKERIZED=True
    depends_on:
      - solr

volumes:
  solr_data:
