version: '2'

services:

  solr:
    image: solr:8
    volumes:
      # NAMED VOLUMES
      - solr_data:/var/solr

  web:
    build:
      context: ./web
    # image: nuremberg:0.15
    tty: true
    command: bash
    volumes:
      # BIND MOUNTS
      - ./web:/nuremberg
    environment:
      # let Django load Docker-specific settings conditionally
      - DOCKERIZED=True
    networks:
      - default
      - minio
    depends_on:
      - solr
      - minio

  minio:
    image: bitnami/minio:2022.8.22
    environment:
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_DEFAULT_BUCKETS=nuremberg-documents:download,nuremberg-transcripts:download
    volumes:
      - minio_data:/data
    networks:
      - minio

networks:
  default:
  minio:

volumes:
  minio_data:
  solr_data:
