# Generated by Django 4.1.2 on 2022-10-10 19:45

from django.db import migrations, models
import nuremberg.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_documentimage_options_add_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=nuremberg.core.storages.DocumentStorage(), upload_to='nuremberg-documents'),
        ),
    ]
