name: Build and publish image

on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tag the branch
        run: |
          export VINNIE_VERSION=`docker compose run --rm web vinnie --semver=False bump`
          echo "vinnie_version=$VINNIE_VERSION" >> $GITHUB_ENV
          git tag $VINNIE_VERSION
          git push --tags

      - name: Login to REVSYS Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.revsys.com
          username: ${{ secrets.REVSYS_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: web
          push: true
          tags: registry.revsys.com/nuremberg:${{ env.vinnie_version }}
